In [28]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [29]:
df = pd.read_csv('Data4.csv')
df

Sl.    x1         x2         x3           y
0     1   0.1   0.311089   0.390541   14.705876
1     2   0.2   0.639066   1.389918   26.585100
2     3   0.3   0.840228   1.939903   36.791509
3     4   0.4   1.299710   2.153009   34.090806
4     5   0.5   0.941784   0.945136   31.118089
..  ...   ...        ...        ...         ...
95   96   9.6  10.336087   9.979673  183.744594
96   97   9.7   9.928599  10.721891  175.907274
97   98   9.8  10.109046  10.163445  183.992845
98   99   9.9   9.954540  10.562039  173.920425
99  100  10.0  10.469087  10.727984  179.018755

[100 rows x 5 columns]

In [30]:
d = 4

In [31]:
df = df.drop("Sl.", axis=1)

In [32]:
df.insert(0,"x0",1)

In [33]:
def Xi_V(index):
    return np.array((df.iloc[index][: d],)).T

In [34]:
def Xi_T_V(index):
    return np.array((df.iloc[index][: d],))

In [35]:
def Yi(index):
    return np.array(df.iloc[index][d:d + 1])

In [36]:
def XiYi_V(index):
    return Xi_V(index) * Yi(index)

In [37]:
zero_vector = np.array([[0.]*d]).T
zero_matrix = zero_vector*zero_vector.T

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
def Sum_XiYi(df):
    s = zero_vector
    for i in range(len(df)):
        s += Xi_V(i) * Yi(i)[0]

    return s

In [39]:
def Sum_XiXiT(df):
    s = zero_matrix
    for i in range(len(df)):
        s += Xi_V(i) @ Xi_T_V(i)

    return s

In [40]:
matrix = Sum_XiXiT(df)
inverse_matrix = np.linalg.inv(matrix)
inverse_matrix

array([[ 0.11668684,  0.0911748 , -0.05419394, -0.04402717],
       [ 0.0911748 ,  0.17232455, -0.13967998, -0.03093789],
       [-0.05419394, -0.13967998,  0.1444378 , -0.00671043],
       [-0.04402717, -0.03093789, -0.00671043,  0.03917373]])

In [41]:
w = np.matmul(inverse_matrix, Sum_XiYi(df))
w

array([[13.23947782],
       [ 6.13243763],
       [ 2.39226554],
       [ 7.74681038]])

In [42]:
def predict(X):
    return np.matmul(w.T , X)

In [43]:
def predicts(df):
    lst = []
    for i in range(len(df)):
        lst.append(list(predict(np.array((df.iloc[i][: d],)).T))[0][0])

    return np.array(lst)

In [44]:
predicted_value = np.array(predicts(df))

In [45]:
df['predicted'] = predicted_value

In [46]:
def Rss(df):
    return np.sum((df['y'] - df['predicted'])**2)

In [47]:
def Tss(df):
    return np.sum((df['y'] - np.mean(df['y']))**2)

In [48]:
def R2(df):
    return 1 - Rss(df) / Tss(df)

In [49]:
R2(df)

0.9841749058943147

In [50]:
LR = LinearRegression()

In [51]:
X =df.drop('y', axis = 1)
X = X.drop('predicted', axis=1)
y = df['y']

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)

In [53]:
x = pd.concat([X_train, X_test], axis=0)
Y = pd.concat([y_train, y_test], axis=0)

In [54]:
LR.fit(X, Y)

LinearRegression()